%% csv_to_mat %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Stuart Oldham, Monash University
%  Date modified: 09-January-2016
%  
%  This script converts the .csv connectome generated by MRtrix3 to a
%  connectome matrix in matlab. Also will remove connections deemed
%  spurious (connections between two nodes that are less than the required
%  threshold. If no desired threshold is entered the script will default to
%  the value used by van den Heuvel et al (2012) i.e. edges with connection
%  strength less than 10 will be removed

function csv_to_mat(CSV_IN_NAME,MAT_OUT_NAME)
    if exist(CSV_IN_NAME, 'file') == 2
        clear y full_y
        y = dlmread(CSV_IN_NAME);
        adj = y + y';
        %if nargin < 3 || isempty(SpuriousStreamValue)
        %    SpuriousStreamValue = 10;
        %else
        %end
    %no_spurious = connectome;
    %no_spurious(no_spurious<SpuriousStreamValue)=0;
%save(MAT_OUT_NAME,'connectome','no_spurious')
save(MAT_OUT_NAME,'adj')
    else
    fprintf(1,'CSV file does not exist\n');
    end
end
