%% csv_to_mat %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Stuart Oldham, Monash University
%  Date modified: 09-January-2016
%  
%  This script converts the .csv connectome generated by MRtrix3 to a
%  connectome matrix in matlab. Also will remove connections deemed
%  spurious (connections between two nodes that are less than the required
%  threshold. If no desired threshold is entered the script will default to
%  the value used by van den Heuvel et al (2012) i.e. edges with connection
%  strength less than 10 will be removed

function csv_to_mat(CSV_IN_NAME,MAT_OUT_NAME)
    if exist(CSV_IN_NAME, 'file')
        clear y full_y
        y = dlmread(CSV_IN_NAME);
        FA_conn = y + y';
save(MAT_OUT_NAME,'FA_conn')
    else
    fprintf(1,'CSV file does not exist\n');
    end
end
